version: '3'

networks:
  backend:
    external: true

services:
  csctracker:
    container_name: auth
    hostname: auth
    image: krlsedu/csctracker-auth
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    ports:
      - "8899:8080"
    networks:
      - backend
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -XX:+UseSerialGC -jar app.jar"
